config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url="orders/", permanent=True)),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("orders/", include("order_manager.urls", namespace="order_manager")),
]


handler404 = "config.views.handler_404"

order_manager/urls.py
from django.urls import path

from order_manager.views import OrderListView, delete_order


urlpatterns = [
    path("", OrderListView.as_view(), name="order-list"),
    path("<int:pk>/", delete_order, name="order-delete")
]

app_name = "order_manager"

order_manager/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser

from order_manager.employee_manager import EmployeeManager


class Employee(AbstractUser):
    class PositionChoices(models.TextChoices):
        JUNIOR = "JR", _("Junior")
        MIDDLE = "ML", _("Middle")
        SENIOR = "SR", _("Senior")

    probation = models.BooleanField(default=True)
    position = models.CharField(
        max_length=2,
        choices=PositionChoices.choices,
        default=PositionChoices.JUNIOR
    )

    objects = EmployeeManager()

    class Meta:
        ordering = ["username"]


class Order(models.Model):
    task_id = models.UUIDField(unique=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    employee = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="orders"
    )

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return str(self.task_id)

config/views.py
from django.shortcuts import render


def handler_404(request, exception):
    return render(request, "404.html", status=404)

order_manager/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from order_manager.models import Order
from order_manager.services.order_service import OrderService


class OrderListView(LoginRequiredMixin, generic.ListView):
    model = Order
    context_object_name = "order_list"
    template_name = "order/order_list.html"
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(employee=self.request.user)


@login_required
def delete_order(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    order = get_object_or_404(Order, pk=pk)
    notification = OrderService.produce_message_notification(order=order)
    messages.info(request, notification)
    order.delete()

    return redirect("order_manager:order-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
  crossorigin="anonymous">
  <title>Wild Wild Leads</title>
</head>
<body>
  <div class="container-fluid">
  <div class="row">
    <div class="col-sm-1">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-10 ">
      <div class="container">
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
              {{ message }}
            </div>
        {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li>{{ user.username }}</li>
    <li><a href="{% url "logout" %}">Logout</a></li>
  {% else %}
    <li><a href="{% url "login" %}">Login</a></li>
  {% endif %}

  <li><a href="{% url "order_manager:order-list" %}">Orders</a></li>
</ul>

templates/order/order_list.html
{% extends "base.html" %}


{% block content %}
  {% if order_list %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Task id</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for order in order_list %}
          <tr>
            <td>{{ order.name }}</td>
            <td>{{ order.description }}</td>
            <td>{{ order.task_id }}</td>
            <td>
              <form action="{% url 'order_manager:order-delete' order.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Delete</button>
              </form>
            </td>
          </tr>
        {% endfor%}
      </tbody>
    </table>
  {% else %}
    <h1>You don't have any orders</h1>
  {% endif %}
{% endblock %}